src/jasontech/jasontech/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('mainsite.urls')),
]

src/jasontech/mainsite/urls.py
from django.urls import path
from . import views

app_name = 'mainsite'
urlpatterns = [
    path('', views.index, name='index'),
    path('about/', views.about, name='about'),
    path('ministry/', views.ministry, name='ministry'),
    path('sermons/', views.sermons, name='sermons'),
    path('events/', views.events, name='events'),
    path('blog/', views.blog, name='blog'),
    path('blog_single/', views.blog_single, name='blog_single'),
    path('contact/', views.contact, name='contact'),
    # path('<int:question_id>/', views.detail, name='detail'),
    # path('<int:question_id>/results/', views.results, name='results'),
    # path('<int:question_id>/vote/', views.vote, name='vote'),
]

src/jasontech/mainsite/models.py
from django.db import models
from django.utils import timezone
# Create your models here.
# 注意縮排

# class Title (models.Model()):

src/jasontech/mainsite/views.py
from django.shortcuts import render
from datetime import datetime
from django.http import HttpResponse

# Create your views here.
def index(request):
    return render(request, 'mainsite/index.html', locals())

def about(request):
    return render(request, 'mainsite/about.html')

def ministry(request):
    return render(request, 'mainsite/ministry.html')

def sermons(request):
    return render(request, 'mainsite/sermons.html')

def events(request):
    return render(request, 'mainsite/events.html')

def blog(request):
    return render(request, 'mainsite/blog.html')

def blog_single(request):
    return render(request, 'mainsite/blog-single.html')

def contact(request):
    return render(request, 'mainsite/contact.html')

src/jasontech/templates/mainsite/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>Spring - Free Bootstrap 4 Template by Colorlib</title>
        <meta charset="utf-8">
        <meta name="viewport"
              content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link href="https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700,800,900"
              rel="stylesheet">
        <link href="https://fonts.googleapis.com/css?family=Raleway:100,200,300,400,500,600,700,800,900"
              rel="stylesheet">
        <link href="https://fonts.googleapis.com/css?family=Crimson+Text:400,400i"
              rel="stylesheet">
        <link rel="stylesheet"
              href="{% static '/mainsite/css/open-iconic-bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static '/mainsite/css/animate.css' %}">
        <link rel="stylesheet"
              href="{% static '/mainsite/css/owl.carousel.min.css' %}">
        <link rel="stylesheet"
              href="{% static '/mainsite/css/owl.theme.default.min.css' %}">
        <link rel="stylesheet"
              href="{% static '/mainsite/css/magnific-popup.css' %}">
        <link rel="stylesheet" href="{% static '/mainsite/css/aos.css' %}">
        <link rel="stylesheet" href="{% static '/mainsite/css/ionicons.min.css' %}">
        <link rel="stylesheet"
              href="{% static '/mainsite/css/bootstrap-datepicker.css' %}">
        <link rel="stylesheet"
              href="{% static '/mainsite/css/jquery.timepicker.css' %}">
        <link rel="stylesheet" href="{% static '/mainsite/css/flaticon.css' %}">
        <link rel="stylesheet" href="{% static '/mainsite/css/icomoon.css' %}">
        <link rel="stylesheet" href="{% static '/mainsite/css/style.css' %}">
    </head>
    <body>
        {% include "mainsite/navbar.html" %}
        {% block content %}{% endblock %}
        {% include "mainsite/footer.html" %}
        <!-- loader -->
        <div id="ftco-loader" class="show fullscreen">
            <svg class="circular" width="48px" height="48px">
                <circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee" />
                <circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10"
                stroke="#F96D00" />
            </svg>
        </div>
        <script src="{% static '/mainsite/js/jquery.min.js' %}"></script>
        <script src="{% static '/mainsite/js/jquery-migrate-3.0.1.min.js' %}"></script>
        <script src="{% static '/mainsite/js/popper.min.js' %}"></script>
        <script src="{% static '/mainsite/js/bootstrap.min.js' %}"></script>
        <script src="{% static '/mainsite/js/jquery.easing.1.3.js' %}"></script>
        <script src="{% static '/mainsite/js/jquery.waypoints.min.js' %}"></script>
        <script src="{% static '/mainsite/js/jquery.stellar.min.js' %}"></script>
        <script src="{% static '/mainsite/js/owl.carousel.min.js' %}"></script>
        <script src="{% static '/mainsite/js/jquery.magnific-popup.min.js' %}"></script>
        <script src="{% static '/mainsite/js/aos.js' %}"></script>
        <script src="{% static '/mainsite/js/jquery.animateNumber.min.js' %}"></script>
        <script src="{% static '/mainsite/js/bootstrap-datepicker.js' %}"></script>
        <script src="{% static '/mainsite/js/jquery.timepicker.min.js' %}"></script>
        <script src="{% static '/mainsite/js/scrollax.min.js' %}"></script>
        <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBVWaKrjvy3MaE7SQ74_uJiULgl1JY0H2s&sensor=false"></script>
        <script src="{% static '/mainsite/js/google-map.js' %}"></script>
        <script src="{% static '/mainsite/js/main.js' %}"></script>
    </body>
</html>

src/jasontech/templates/mainsite/blog.html
{% extends "mainsite/base.html" %}
{% load static %}
{% block content %}
    <section class="hero-wrap hero-wrap-2"
             style="background-image: url('{% static "/mainsite/images/bg_2.jpg" %}');"
             data-stellar-background-ratio="0.5">
        <div class="overlay"></div>
        <div class="container">
            <div class="row no-gutters slider-text align-items-end justify-content-center">
                <div class="col-md-9 ftco-animate pb-5 text-center">
                    <h1 class="mb-2 bread">Our Blog</h1>
                    <p class="breadcrumbs">
                        <span class="mr-2"><a href="{% url 'mainsite:index' %}">Home <i class="ion-ios-arrow-forward"></i></a></span> <span>Blog <i class="ion-ios-arrow-forward"></i></span>
                    </p>
                </div>
            </div>
        </div>
    </section>
    <section class="ftco-section bg-light">
        <div class="container">
            <div class="row d-flex">
                <div class="col-lg-4 d-flex ftco-animate">
                    <div class="blog-entry justify-content-end">
                        <a href="{% url 'mainsite:blog_single' %}"
                           class="block-20"
                           style="background-image: url('{% static "/mainsite/images/image_1.jpg" %}');"></a>
                        <div class="text d-flex float-right d-block">
                            <div class="topper text-center pt-4 px-3">
                                <span class="day">18</span>
                                <span class="mos">January</span>
                                <span class="yr">2019</span>
                            </div>
                            <div class="desc p-4">
                                <h3 class="heading mt-2">
                                    <a href="#">All you want to know about Bible</a>
                                </h3>
                                <p>A small river named Duden flows by their place and supplies it with the necessary regelialia.</p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4 d-flex ftco-animate">
                    <div class="blog-entry justify-content-end">
                        <a href="{% url 'mainsite:blog_single' %}"
                           class="block-20"
                           style="background-image: url('{% static "/mainsite/images/image_2.jpg" %}');"></a>
                        <div class="text d-flex float-right d-block">
                            <div class="topper text-center pt-4 px-3">
                                <span class="day">15</span>
                                <span class="mos">January</span>
                                <span class="yr">2019</span>
                            </div>
                            <div class="desc p-4">
                                <h3 class="heading mt-2">
                                    <a href="#">All you want to know about Bible</a>
                                </h3>
                                <p>A small river named Duden flows by their place and supplies it with the necessary regelialia.</p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4 d-flex ftco-animate">
                    <div class="blog-entry">
                        <a href="{% url 'mainsite:blog_single' %}"
                           class="block-20"
                           style="background-image: url('{% static "/mainsite/images/image_3.jpg" %}');"></a>
                        <div class="text d-flex float-right d-block">
                            <div class="topper text-center pt-4 px-3">
                                <span class="day">14</span>
                                <span class="mos">January</span>
                                <span class="yr">2019</span>
                            </div>
                            <div class="desc p-4">
                                <h3 class="heading mt-2">
                                    <a href="#">All you want to know about Bible</a>
                                </h3>
                                <p>A small river named Duden flows by their place and supplies it with the necessary regelialia.</p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4 d-flex ftco-animate">
                    <div class="blog-entry justify-content-end">
                        <a href="{% url 'mainsite:blog_single' %}"
                           class="block-20"
                           style="background-image: url('{% static "/mainsite/images/image_4.jpg" %}');"></a>
                        <div class="text d-flex float-right d-block">
                            <div class="topper text-center pt-4 px-3">
                                <span class="day">18</span>
                                <span class="mos">January</span>
                                <span class="yr">2019</span>
                            </div>
                            <div class="desc p-4">
                                <h3 class="heading mt-2">
                                    <a href="#">All you want to know about Bible</a>
                                </h3>
                                <p>A small river named Duden flows by their place and supplies it with the necessary regelialia.</p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4 d-flex ftco-animate">
                    <div class="blog-entry justify-content-end">
                        <a href="{% url 'mainsite:blog_single' %}"
                           class="block-20"
                           style="background-image: url('{% static "/mainsite/images/image_5.jpg" %}');">
                        </a>
                        <div class="text d-flex float-right d-block">
                            <div class="topper text-center pt-4 px-3">
                                <span class="day">15</span>
                                <span class="mos">January</span>
                                <span class="yr">2019</span>
                            </div>
                            <div class="desc p-4">
                                <h3 class="heading mt-2">
                                    <a href="#">All you want to know about Bible</a>
                                </h3>
                                <p>
                                    A small river named Duden flows by their place and supplies it with the necessary regelialia.
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="col-lg-4 d-flex ftco-animate">
                    <div class="blog-entry">
                        <a href="{% url 'mainsite:blog_single' %}"
                           class="block-20"
                           style="background-image: url('{% static "/mainsite/images/image_6.jpg" %}');">
                        </a>
                        <div class="text d-flex float-right d-block">
                            <div class="topper text-center pt-4 px-3">
                                <span class="day">14</span>
                                <span class="mos">January</span>
                                <span class="yr">2019</span>
                            </div>
                            <div class="desc p-4">
                                <h3 class="heading mt-2">
                                    <a href="#">All you want to know about Bible</a>
                                </h3>
                                <p>
                                    A small river named Duden flows by their place and supplies it with the necessary regelialia.
                                </p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row mt-5">
                <div class="col text-center">
                    <div class="block-27">
                        <ul>
                            <li>
                                <a href="#">&lt;</a>
                            </li>
                            <li class="active">
                                <span>1</span>
                            </li>
                            <li>
                                <a href="#">2</a>
                            </li>
                            <li>
                                <a href="#">3</a>
                            </li>
                            <li>
                                <a href="#">4</a>
                            </li>
                            <li>
                                <a href="#">5</a>
                            </li>
                            <li>
                                <a href="#">&gt;</a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

src/jasontech/templates/mainsite/contact.html
{% extends "mainsite/base.html" %}
{% load static %}
{% block content %}
    <section class="hero-wrap hero-wrap-2"
             style="background-image: url('{% static "/mainsite/images/bg_2.jpg" %}');"
             data-stellar-background-ratio="0.5">
        <div class="overlay"></div>
        <div class="container">
            <div class="row no-gutters slider-text align-items-end justify-content-center">
                <div class="col-md-9 ftco-animate pb-5 text-center">
                    <h1 class="mb-2 bread">Contact Us</h1>
                    <p class="breadcrumbs">
                        <span class="mr-2"><a href="{% url 'mainsite:index' %}">Home <i class="ion-ios-arrow-forward"></i></a></span> <span>Contact <i class="ion-ios-arrow-forward"></i></span>
                    </p>
                </div>
            </div>
        </div>
    </section>
    <section class="ftco-daily-verse bg-light">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-md-10 daily-verse text-center p-5">
                    <span class="flaticon-bible"></span>
                    <h3 class="ftco-animate">
                        "16 For God so loved the world, that he gave his only begotten Son, that whosoever believeth in him should not perish, but have everlasting life."
                    </h3>
                    <h4 class="h5 mt-4 font-weight-bold ftco-animate">&mdash; John 3:16 KJV</h4>
                </div>
            </div>
        </div>
    </section>
    <section class="ftco-section contact-section">
        <div class="container">
            <div class="row d-flex mb-5 contact-info">
                <div class="col-md-12 mb-4">
                    <h2 class="h3">Contact Information</h2>
                </div>
                <div class="w-100"></div>
                <div class="col-md-3">
                    <p>
                        <span>Address:</span> 198 West 21th Street, Suite 721 New York NY 10016
                    </p>
                </div>
                <div class="col-md-3">
                    <p>
                        <span>Phone:</span> <a href="tel:+886-1234567920">+0912345678</a>
                    </p>
                </div>
                <div class="col-md-3">
                    <p>
                        <span>Email:</span> <a href="mailto:info@yoursite.com">info@yoursite.com</a>
                    </p>
                </div>
                <div class="col-md-3">
                    <p>
                        <span>Website</span> <a href="#">yoursite.com</a>
                    </p>
                </div>
            </div>
            <div class="row block-9">
                <div class="col-lg-6 order-md-last d-flex">
                    <form action="#" class="bg-light p-5 contact-form">
                        <div class="form-group">
                            <input type="text" class="form-control" placeholder="Your Name">
                        </div>
                        <div class="form-group">
                            <input type="text" class="form-control" placeholder="Your Email">
                        </div>
                        <div class="form-group">
                            <input type="text" class="form-control" placeholder="Subject">
                        </div>
                        <div class="form-group">
                            <textarea name=""
                                      id=""
                                      cols="30"
                                      rows="7"
                                      class="form-control"
                                      placeholder="Message"></textarea>
                        </div>
                        <div class="form-group">
                            <input type="submit" value="Send Message" class="btn btn-primary py-3 px-5">
                        </div>
                    </form>
                </div>
                <div class="col-lg-6 d-flex">
                    <div id="map" class="bg-white"></div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

src/jasontech/templates/mainsite/footer.html
<section class="ftco-section ftco-section-parallax bg-secondary ftco-no-pb">
    <div class="parallax-img d-flex align-items-center">
        <div class="container">
            <div class="row d-flex justify-content-center">
                <div class="col-md-7 text-center heading-section heading-section-white heading-section-no-line ftco-animate">
                    <h2>Newsletter</h2>
                    <p>
                        Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts. Separated they live in
                    </p>
                    <div class="row d-flex justify-content-center mt-4 mb-4">
                        <div class="col-md-8">
                            <form action="#" class="subscribe-form">
                                <div class="form-group d-flex">
                                    <input type="text" class="form-control" placeholder="Enter email address">
                                    <input type="submit" value="Subscribe" class="submit px-3">
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<footer class="ftco-footer ftco-bg-dark ftco-section">
    <div class="container">
        <div class="row mb-5">
            <div class="col-md">
                <div class="ftco-footer-widget mb-4">
                    <h2 class="ftco-heading-2">Spring Church</h2>
                    <p>
                        Far far away, behind the word mountains, far from the countries Vokalia and Consonantia, there live the blind texts.
                    </p>
                    <ul class="ftco-footer-social list-unstyled float-md-left float-lft mt-5">
                        <li class="ftco-animate">
                            <a href="#"><span class="icon-twitter"></span></a>
                        </li>
                        <li class="ftco-animate">
                            <a href="#"><span class="icon-facebook"></span></a>
                        </li>
                        <li class="ftco-animate">
                            <a href="#"><span class="icon-instagram"></span></a>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="col-md">
                <div class="ftco-footer-widget mb-4 ml-md-5">
                    <h2 class="ftco-heading-2">About</h2>
                    <ul class="list-unstyled">
                        <li>
                            <a href="#" class="py-1 d-block"><span class="ion-ios-arrow-forward mr-3"></span>Staff</a>
                        </li>
                        <li>
                            <a href="#" class="py-1 d-block"><span class="ion-ios-arrow-forward mr-3"></span>Beliefs</a>
                        </li>
                        <li>
                            <a href="#" class="py-1 d-block"><span class="ion-ios-arrow-forward mr-3"></span>History</a>
                        </li>
                        <li>
                            <a href="#" class="py-1 d-block"><span class="ion-ios-arrow-forward mr-3"></span>Mission</a>
                        </li>
                        <li>
                            <a href="#" class="py-1 d-block"><span class="ion-ios-arrow-forward mr-3"></span>Wedding &amp; Funerals</a>
                        </li>
                        <li>
                            <a href="#" class="py-1 d-block"><span class="ion-ios-arrow-forward mr-3"></span>Jobs &amp; Internship</a>
                        </li>
                        <li>
                            <a href="#" class="py-1 d-block"><span class="ion-ios-arrow-forward mr-3"></span>Fellowships</a>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="col-md">
                <div class="ftco-footer-widget mb-4 ml-md-5">
                    <h2 class="ftco-heading-2">Connect</h2>
                    <ul class="list-unstyled">
                        <li>
                            <a href="#" class="py-1 d-block"><span class="ion-ios-arrow-forward mr-3"></span>Home Groups</a>
                        </li>
                        <li>
                            <a href="#" class="py-1 d-block"><span class="ion-ios-arrow-forward mr-3"></span>Recovery Groups</a>
                        </li>
                        <li>
                            <a href="#" class="py-1 d-block"><span class="ion-ios-arrow-forward mr-3"></span>Memberships</a>
                        </li>
                        <li>
                            <a href="#" class="py-1 d-block"><span class="ion-ios-arrow-forward mr-3"></span>Children &amp; Students</a>
                        </li>
                        <li>
                            <a href="#" class="py-1 d-block"><span class="ion-ios-arrow-forward mr-3"></span>Volunteer</a>
                        </li>
                        <li>
                            <a href="#" class="py-1 d-block"><span class="ion-ios-arrow-forward mr-3"></span>Counseling</a>
                        </li>
                        <li>
                            <a href="#" class="py-1 d-block"><span class="ion-ios-arrow-forward mr-3"></span>Assistance</a>
                        </li>
                    </ul>
                </div>
            </div>
            <div class="col-md">
                <div class="ftco-footer-widget mb-4">
                    <h2 class="ftco-heading-2">Service Hours</h2>
                    <div class="opening-hours">
                        <h4>Services Hours</h4>
                        <p class="pl-3">
                            <span class="mb-3">Saturday Prayer Meeting &mdash; 10:00 am to 11:30 am</span>
                            <span>Sunday Service &mdash; 8:30 am to 11:30 am</span>
                        </p>
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12 text-center">
                <p>
                    <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                    Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved | This template is made with <i class="icon-heart color-danger" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
                    <!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                </p>
            </div>
        </div>
    </div>
</footer>

src/jasontech/templates/mainsite/ministry.html
{% extends "mainsite/base.html" %}
{% load static %}
{% block content %}
    <section class="hero-wrap hero-wrap-2"
             style="background-image: url('{% static "/mainsite/images/bg_2.jpg" %}');"
             data-stellar-background-ratio="0.5">
        <div class="overlay"></div>
        <div class="container">
            <div class="row no-gutters slider-text align-items-end justify-content-center">
                <div class="col-md-9 ftco-animate pb-5 text-center">
                    <h1 class="mb-2 bread">Youth &amp; Family</h1>
                    <p class="breadcrumbs">
                        <span class="mr-2"><a href="{% url 'mainsite:index' %}">Home <i class="ion-ios-arrow-forward"></i></a></span> <span>Ministry <i class="ion-ios-arrow-forward"></i></span>
                    </p>
                </div>
            </div>
        </div>
    </section>
    <section class="ftco-section">
        <div class="container">
            <div class="row">
                <div class="col-md-3">
                    <ul class="ministry-list">
                        <li class="active">
                            <a href="#">Youth &amp; Family</a>
                        </li>
                        <li>
                            <a href="#">Community Outreach</a>
                        </li>
                        <li>
                            <a href="#">Missions</a>
                        </li>
                    </ul>
                </div>
                <div class="col-md-9">
                    <h3 class="mb-4">Opportunities</h3>
                    <p>
                        Even the all-powerful Pointing has no control about the blind texts it is an almost unorthographic life One day however a small line of blind text by the name of Lorem Ipsum decided to leave for the far World of Grammar.
                    </p>
                    <ul class="ministry-list my-5">
                        <li>
                            <span class="ion-ios-arrow-forward mr-2"></span>Bible classes for all ages
                        </li>
                        <li>
                            <span class="ion-ios-arrow-forward mr-2"></span>The Big Oxmox advised her not to do so
                        </li>
                        <li>
                            <span class="ion-ios-arrow-forward mr-2"></span>Pointing has no control about
                        </li>
                        <li>
                            <span class="ion-ios-arrow-forward mr-2"></span>Separated they live in Bookmarksgrove right
                        </li>
                    </ul>
                    <hr>
                    <h3 class="mb-4 mt-5">The Lord's Army</h3>
                    <p>
                        Even the all-powerful Pointing has no control about the blind texts it is an almost unorthographic life One day however a small line of blind text by the name of Lorem Ipsum decided to leave for the far World of Grammar.
                    </p>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

src/jasontech/templates/mainsite/navbar.html
<nav class="navbar navbar-dark ftco_navbar bg-dark ftco-navbar-light"
     id="ftco-navbar">
    <div class="container d-flex align-items-stretch">
        <div class="col-3 d-flex align-items-center">
            <a class="navbar-brand" href="{% url 'mainsite:index' %}">Spring<span>Church</span></a>
        </div>
        <div class="col-9 d-flex align-items-center text-right">
            <ul class="ftco-social mt-2 mr-3">
                <li class="ftco-animate">
                    <a href="#"><span class="icon-twitter"></span></a>
                </li>
                <li class="ftco-animate">
                    <a href="#"><span class="icon-facebook"></span></a>
                </li>
                <li class="ftco-animate">
                    <a href="#"><span class="icon-instagram"></span></a>
                </li>
            </ul>
            <button class="navbar-toggler d-flex align-items-center"
                    type="button"
                    data-toggle="collapse"
                    data-target="#ftco-nav"
                    aria-controls="ftco-nav"
                    aria-expanded="false"
                    aria-label="Toggle navigation">
                <span class="pt-1 mr-1">Menu</span> <span class="oi oi-menu"></span>
            </button>
        </div>
        <div class="collapse navbar-collapse" id="ftco-nav">
            <ul class="navbar-nav ml-auto">
                {% comment %} active 使用 javascript 解析 url {% endcomment %}
                <li class="nav-item active">
                    <a href="{% url 'mainsite:index' %}" class="nav-link">Home</a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'mainsite:about' %}" class="nav-link">About</a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'mainsite:ministry' %}" class="nav-link">Ministries</a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'mainsite:sermons' %}" class="nav-link">Sermons</a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'mainsite:events' %}" class="nav-link">Upcoming Events</a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'mainsite:blog' %}" class="nav-link">Blog</a>
                </li>
                <li class="nav-item">
                    <a href="{% url 'mainsite:contact' %}" class="nav-link">Contact</a>
                </li>
            </ul>
        </div>
    </div>
</nav>
<!-- END nav -->